2018-04-17 09:23:45,674 [Thread-7:12212] [django.request:152] [base:get_response] [WARNING]- Not Found: /
2018-04-17 10:00:08,904 [Thread-8:11972] [django.request:152] [base:get_response] [WARNING]- Not Found: /favicon.ico
2018-04-17 11:39:19,384 [Thread-1:9340] [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /redistools/search-form/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\learndjango\Redis3Tools\redistools\sso_check.py", line 18, in _wrap
    return func(request, *args, **kwargs)
  File "D:\learndjango\Redis3Tools\redistools\search.py", line 42, in search_form
    return render_to_response('search_form.html')
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 21, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\defaulttags.py", line 458, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Python27\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Python27\lib\site-packages\django\urls\resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
NoReverseMatch: Reverse for 'qm-dashboard' not found. 'qm-dashboard' is not a valid view function or pattern name.
2018-04-17 11:40:56,576 [Thread-3:2832] [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /redistools/search-form/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\learndjango\Redis3Tools\redistools\sso_check.py", line 18, in _wrap
    return func(request, *args, **kwargs)
  File "D:\learndjango\Redis3Tools\redistools\search.py", line 42, in search_form
    return render_to_response('search_form.html')
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 21, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\defaulttags.py", line 458, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Python27\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Python27\lib\site-packages\django\urls\resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
NoReverseMatch: Reverse for 'redistools/search-form' not found. 'redistools/search-form' is not a valid view function or pattern name.
2018-04-17 11:41:32,688 [Thread-4:1824] [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /redistools/search-form/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\learndjango\Redis3Tools\redistools\sso_check.py", line 18, in _wrap
    return func(request, *args, **kwargs)
  File "D:\learndjango\Redis3Tools\redistools\search.py", line 42, in search_form
    return render_to_response('search_form.html')
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 21, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\defaulttags.py", line 458, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Python27\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Python27\lib\site-packages\django\urls\resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
NoReverseMatch: Reverse for '/redistools/search-form/' not found. '/redistools/search-form/' is not a valid view function or pattern name.
2018-04-17 11:43:39,736 [Thread-5:9084] [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /redistools/search-form/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\learndjango\Redis3Tools\redistools\sso_check.py", line 18, in _wrap
    return func(request, *args, **kwargs)
  File "D:\learndjango\Redis3Tools\redistools\search.py", line 42, in search_form
    return render_to_response('search_form.html')
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 21, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\defaulttags.py", line 458, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Python27\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Python27\lib\site-packages\django\urls\resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
2018-04-17 14:01:08,467 [Thread-1:11464] [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /redistools/search-form/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\learndjango\Redis3Tools\redistools\sso_check.py", line 17, in _wrap
    return func(request, *args, **kwargs)
  File "D:\learndjango\Redis3Tools\redistools\search.py", line 42, in search_form
    return render_to_response('search_form.html')
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 21, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\defaulttags.py", line 458, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Python27\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Python27\lib\site-packages\django\urls\resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
NoReverseMatch: Reverse for '/redistools/login' not found. '/redistools/login' is not a valid view function or pattern name.
2018-04-17 15:23:50,414 [Thread-1:7916] [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /redistools/search-form/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\learndjango\Redis3Tools\redistools\sso_check.py", line 17, in _wrap
    return func(request, *args, **kwargs)
  File "D:\learndjango\Redis3Tools\redistools\search.py", line 42, in search_form
    return render_to_response('search_form.html')
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 21, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 154, in render
    compiled_parent = self.get_parent(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 151, in get_parent
    return self.find_template(parent, context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 131, in find_template
    template_name, skip=history,
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 136, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\Python27\lib\site-packages\django\template\loaders\base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\Python27\lib\site-packages\django\template\base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 230, in compile_nodelist
    return parser.parse()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 509, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 571, in invalid_block_tag
    "or load this tag?" % (token.lineno, command)
TemplateSyntaxError: Invalid block tag on line 8: 'static'. Did you forget to register or load this tag?
2018-04-17 15:23:51,283 [Thread-3:3060] [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /redistools/search-form/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\learndjango\Redis3Tools\redistools\sso_check.py", line 17, in _wrap
    return func(request, *args, **kwargs)
  File "D:\learndjango\Redis3Tools\redistools\search.py", line 42, in search_form
    return render_to_response('search_form.html')
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 21, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 154, in render
    compiled_parent = self.get_parent(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 151, in get_parent
    return self.find_template(parent, context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 131, in find_template
    template_name, skip=history,
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 136, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\Python27\lib\site-packages\django\template\loaders\base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\Python27\lib\site-packages\django\template\base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 230, in compile_nodelist
    return parser.parse()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 509, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 571, in invalid_block_tag
    "or load this tag?" % (token.lineno, command)
TemplateSyntaxError: Invalid block tag on line 8: 'static'. Did you forget to register or load this tag?
2018-04-17 15:23:59,311 [Thread-4:8356] [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /redistools/search-form/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\learndjango\Redis3Tools\redistools\sso_check.py", line 17, in _wrap
    return func(request, *args, **kwargs)
  File "D:\learndjango\Redis3Tools\redistools\search.py", line 42, in search_form
    return render_to_response('search_form.html')
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 21, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 154, in render
    compiled_parent = self.get_parent(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 151, in get_parent
    return self.find_template(parent, context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 131, in find_template
    template_name, skip=history,
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 136, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\Python27\lib\site-packages\django\template\loaders\base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\Python27\lib\site-packages\django\template\base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 230, in compile_nodelist
    return parser.parse()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 509, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 571, in invalid_block_tag
    "or load this tag?" % (token.lineno, command)
TemplateSyntaxError: Invalid block tag on line 8: 'static'. Did you forget to register or load this tag?
2018-04-17 16:38:13,637 [Thread-26:11892] [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /redistools/search-form/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\learndjango\Redis3Tools\redistools\sso_check.py", line 17, in _wrap
    return func(request, *args, **kwargs)
  File "D:\learndjango\Redis3Tools\redistools\search.py", line 43, in search_form
    return render_to_response('search_form.html')
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 21, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 162, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 136, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\Python27\lib\site-packages\django\template\loaders\base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\Python27\lib\site-packages\django\template\base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 230, in compile_nodelist
    return parser.parse()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 516, in parse
    self.extend_nodelist(nodelist, compiled_result, token)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 534, in extend_nodelist
    token, '%r must be the first tag in the template.' % node,
TemplateSyntaxError: <ExtendsNode: extends "menu.html"> must be the first tag in the template.
2018-04-18 13:55:06,921 [Thread-4:10612] [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /redistools/search/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\learndjango\Redis3Tools\redistools\sso_check.py", line 17, in _wrap
    return func(request, *args, **kwargs)
  File "D:\learndjango\Redis3Tools\redistools\search.py", line 69, in search
    username, redistype, namespace, keys.result_list))
AttributeError: 'unicode' object has no attribute 'result_list'
2018-04-18 13:55:25,206 [Thread-5:12108] [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /redistools/search/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\learndjango\Redis3Tools\redistools\sso_check.py", line 17, in _wrap
    return func(request, *args, **kwargs)
  File "D:\learndjango\Redis3Tools\redistools\search.py", line 69, in search
    username, redistype, namespace, keys.result_list))
AttributeError: 'unicode' object has no attribute 'result_list'
2018-04-18 13:57:43,526 [Thread-1:6364] [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /redistools/search/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\learndjango\Redis3Tools\redistools\sso_check.py", line 17, in _wrap
    return func(request, *args, **kwargs)
  File "D:\learndjango\Redis3Tools\redistools\search.py", line 69, in search
    username, redistype, namespace, keys.result_list))
AttributeError: 'unicode' object has no attribute 'result_list'
2018-04-18 13:58:13,216 [Thread-13:8496] [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /redistools/search/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\learndjango\Redis3Tools\redistools\sso_check.py", line 17, in _wrap
    return func(request, *args, **kwargs)
  File "D:\learndjango\Redis3Tools\redistools\search.py", line 69, in search
    username, redistype, namespace, keys.result_list))
AttributeError: 'unicode' object has no attribute 'result_list'
2018-04-18 14:00:02,424 [Thread-14:12368] [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /redistools/search/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view redistools.sso_check._wrap didn't return an HttpResponse object. It returned None instead.
2018-04-18 14:00:26,023 [Thread-16:9348] [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /redistools/search/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view redistools.sso_check._wrap didn't return an HttpResponse object. It returned None instead.
2018-04-18 14:00:26,970 [Thread-18:13280] [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /redistools/search/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view redistools.sso_check._wrap didn't return an HttpResponse object. It returned None instead.
2018-04-18 14:00:27,947 [Thread-20:12924] [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /redistools/search/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view redistools.sso_check._wrap didn't return an HttpResponse object. It returned None instead.
2018-04-18 14:00:58,089 [Thread-28:9752] [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /redistools/search/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\learndjango\Redis3Tools\redistools\sso_check.py", line 17, in _wrap
    return func(request, *args, **kwargs)
  File "D:\learndjango\Redis3Tools\redistools\search.py", line 69, in search
    username, redistype, namespace, keys.result_list))
AttributeError: 'unicode' object has no attribute 'result_list'
2018-04-18 14:01:26,744 [Thread-31:10304] [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /redistools/search/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\learndjango\Redis3Tools\redistools\sso_check.py", line 17, in _wrap
    return func(request, *args, **kwargs)
  File "D:\learndjango\Redis3Tools\redistools\search.py", line 69, in search
    username, redistype, namespace, keys.result_list))
AttributeError: 'unicode' object has no attribute 'result_list'
2018-04-18 14:01:53,658 [Thread-70:3148] [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /redistools/search/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\learndjango\Redis3Tools\redistools\sso_check.py", line 17, in _wrap
    return func(request, *args, **kwargs)
  File "D:\learndjango\Redis3Tools\redistools\search.py", line 69, in search
    username, redistype, namespace, keys.result_list))
AttributeError: 'unicode' object has no attribute 'result_list'
2018-04-18 14:02:42,881 [Thread-4:10712] [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /redistools/search/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\learndjango\Redis3Tools\redistools\sso_check.py", line 17, in _wrap
    return func(request, *args, **kwargs)
  File "D:\learndjango\Redis3Tools\redistools\search.py", line 69, in search
    username, redistype, namespace, keys.result_list))
AttributeError: 'unicode' object has no attribute 'result_list'
2018-04-18 14:17:44,786 [Thread-9:11312] [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /redistools/search/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:/learndjango/Redis3Tools\redistools\sso_check.py", line 17, in _wrap
    return func(request, *args, **kwargs)
  File "D:/learndjango/Redis3Tools\redistools\search.py", line 69, in search
    username, redistype, namespace, keys.result_list))
AttributeError: 'unicode' object has no attribute 'result_list'
